import "./globals.css";
import type { Metadata } from "next";

import Navbar from "./navbar";
import Footer from "./footer";
import { Montserrat, Playfair_Display } from "next/font/google";

const inter = Montserrat({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const roboto_mono = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable}`}>
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:p-4 focus:bg-white focus:text-black focus:outline-none"
      >
        Skip to main content
      </a>
      <body>
        <Navbar />
        {children}
      </body>
      <Footer />
    </html>
  );
}
